In [1]:
import tensorflow as tf

In [ ]:
print(tf.__version__)

2.14.0


## 1D Tensors

In [ ]:
tensor_zero_d = tf.constant(4)

In [ ]:
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
tensor_zero_d = tf.constant([2, 0, -3, 8, 10.])
print(tensor_zero_d)

tf.Tensor([ 2.  0. -3.  8. 10.], shape=(5,), dtype=float32)


In [ ]:
casted_tensor_zero_d = tf.cast(
    tensor_zero_d, dtype=tf.int64
)

In [ ]:
print(casted_tensor_zero_d)

tf.Tensor([ 2  0 -3  8 10], shape=(5,), dtype=int64)


In [ ]:
tf.cast(
    tensor_zero_d, dtype=bool
)

<tf.Tensor: shape=(5,), dtype=bool, numpy=array([ True, False,  True,  True,  True])>

## 2D Tensors

In [27]:
tensor_two_d = tf.constant([
    [1, 2, 0],
    [3, 5, -2],
    [1, 5, 6],
    [2, 3, 8],
])

In [ ]:
print(tensor_two_d)
print(tensor_two_d.ndim)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -2]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)
2


## 3D Tensors

In [ ]:
tensor_three_d = tf.constant([
    [[1, 2, 0],
    [3, 5, -2],
    [1, 5, 6],
    [2, 3, 8],],
    [[1, 2, 0],
    [3, 5, -2],
    [3, 5, -2],
    [2, 3, 8],],
])

In [ ]:
print(tensor_three_d)

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -2]
  [ 1  5  6]
  [ 2  3  8]]

 [[ 1  2  0]
  [ 3  5 -2]
  [ 3  5 -2]
  [ 2  3  8]]], shape=(2, 4, 3), dtype=int32)


In [ ]:
print(tensor_three_d.shape)

(2, 4, 3)


In [ ]:
print(tensor_three_d.ndim)

3


## 4D Tensors

In [ ]:
tensor_four_d = tf.constant([
      [
        [[1, 2, 0],
        [2, 3, 8],],

        [[1, 2, 0],
        [2, 3, 8],],

        [[1, 2, 0],
        [2, 3, 8],],

        [[1, 2, 0],
        [2, 3, 8],],
      ],
      [
        [[5, 25, 123],
        [235, 3, 198],],

        [[1, 21, 53],
        [200, 328, 8],],

        [[15, 23, 5],
        [2, 3, 89],],

        [[1, 2, 90],
        [22, 36, 87],],
      ],
      [
        [[5, 25, 123],
        [235, 3, 198],],

        [[1, 21, 53],
        [200, 328, 8],],

        [[15, 23, 5],
        [2, 3, 89],],

        [[1, 2, 90],
        [22, 36, 87],],
      ]
], dtype=tf.float32)

In [ ]:
print(tensor_four_d)
print(tensor_four_d.shape)
print(tensor_four_d.ndim)

tf.Tensor(
[[[[  1.   2.   0.]
   [  2.   3.   8.]]

  [[  1.   2.   0.]
   [  2.   3.   8.]]

  [[  1.   2.   0.]
   [  2.   3.   8.]]

  [[  1.   2.   0.]
   [  2.   3.   8.]]]


 [[[  5.  25. 123.]
   [235.   3. 198.]]

  [[  1.  21.  53.]
   [200. 328.   8.]]

  [[ 15.  23.   5.]
   [  2.   3.  89.]]

  [[  1.   2.  90.]
   [ 22.  36.  87.]]]


 [[[  5.  25. 123.]
   [235.   3. 198.]]

  [[  1.  21.  53.]
   [200. 328.   8.]]

  [[ 15.  23.   5.]
   [  2.   3.  89.]]

  [[  1.   2.  90.]
   [ 22.  36.  87.]]]], shape=(3, 4, 2, 3), dtype=float32)
(3, 4, 2, 3)
4


## Complex Data Type

In [ ]:
real = tf.constant([2.25])
imag = tf.constant([4.75])
tf.complex(real, imag)

<tf.Tensor: shape=(1,), dtype=complex64, numpy=array([2.25+4.75j], dtype=complex64)>

## Tensor String

In [ ]:
tensor_string = tf.constant(["hello world", "hi"])
print(tensor_string)

tf.Tensor([b'hello world' b'hi'], shape=(2,), dtype=string)


## Numpy to Tensorflow

In [ ]:
import numpy as np

In [ ]:
np_array = np.array([1,2,3])

In [ ]:
print(np_array.shape)

(3,)


In [ ]:
converted_tensor = tf.convert_to_tensor(np_array)

In [ ]:
print(converted_tensor)

tf.Tensor([1 2 3], shape=(3,), dtype=int64)


In [ ]:
#let's us create multi dimensional identity matrix tensors using tf.eye function
tf.eye(
    num_rows=5,
    num_columns=None,
    batch_shape=[3],
    dtype=tf.dtypes.bool,
    name=None
)

<tf.Tensor: shape=(3, 5, 5), dtype=bool, numpy=
array([[[ True, False, False, False, False],
        [False,  True, False, False, False],
        [False, False,  True, False, False],
        [False, False, False,  True, False],
        [False, False, False, False,  True]],

       [[ True, False, False, False, False],
        [False,  True, False, False, False],
        [False, False,  True, False, False],
        [False, False, False,  True, False],
        [False, False, False, False,  True]],

       [[ True, False, False, False, False],
        [False,  True, False, False, False],
        [False, False,  True, False, False],
        [False, False, False,  True, False],
        [False, False, False, False,  True]]])>

In [ ]:
#tensors filled with 1
tf.ones(
    [2,3,2,2],
    dtype=tf.dtypes.float16,
    name=None,
    layout=None
)

<tf.Tensor: shape=(2, 3, 2, 2), dtype=float16, numpy=
array([[[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]], dtype=float16)>

In [ ]:
#tensors filled with 0
tf.zeros(
    [2,],
    dtype=tf.dtypes.float16,
    name=None,
    layout=None
)

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([0., 0.], dtype=float16)>

In [ ]:
#tensors filled with custom values
tensor_ten_filled = tf.fill(
    [2,2,3],
    2*5.0,
)

In [ ]:
#gives a tensor filled with 1 of the similar shape of the tensor given as input.
tf.ones_like(tensor_ten_filled)

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [ ]:
random_tensor = tf.constant([
    [1,1,1],
    [1,1,1],
    [1,1,1],
])
print(random_tensor)

tf.Tensor(
[[1 1 1]
 [1 1 1]
 [1 1 1]], shape=(3, 3), dtype=int32)


In [ ]:
print(tf.shape(random_tensor))
print(tf.size(random_tensor))
print(tf.rank(random_tensor))

tf.Tensor([3 3], shape=(2,), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


## Tensors from Normal Distribution

In [ ]:
tf.random.set_seed(
    5
)

In [ ]:
normal_dist_tensor = tf.random.normal(
    [2,2],
    mean=6.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=5,
    name=None
)
print(normal_dist_tensor)

tf.Tensor(
[[4.2759366 7.153922 ]
 [6.6372123 6.168168 ]], shape=(2, 2), dtype=float32)


In [ ]:
# setting global seed value to 5.
tf.random.set_seed(5)

random_tensor = tf.random.uniform(
    [4,4],
    minval=4,
    maxval=80,
    dtype=tf.dtypes.int32,
    seed=5,
    name=None
)
print(random_tensor)

tf.Tensor(
[[48 43 52 39]
 [72 39 34  6]
 [58 66 68 20]
 [15  8 50 11]], shape=(4, 4), dtype=int32)


## Tensor Indexing

In [ ]:
oned_tensor_indexed = tf.random.uniform([5,], minval=2, maxval=10, dtype=tf.dtypes.int32)

In [ ]:
print(oned_tensor_indexed)
print(oned_tensor_indexed[4::-1])

tf.Tensor([8 9 2 8 5], shape=(5,), dtype=int32)
tf.Tensor([5 8 2 9 8], shape=(5,), dtype=int32)


In [ ]:
twod_tensor_indexed = tf.random.uniform([5,5], minval=2, maxval=10, dtype=tf.dtypes.int32)

In [ ]:
#indexing with 2d tensors
print(twod_tensor_indexed)
print(twod_tensor_indexed[3::-1,2:4])

tf.Tensor(
[[7 6 2 8 8]
 [3 6 9 3 8]
 [2 7 5 2 8]
 [2 6 9 3 5]
 [3 8 4 8 3]], shape=(5, 5), dtype=int32)
tf.Tensor(
[[9 3]
 [5 2]
 [9 3]
 [2 8]], shape=(4, 2), dtype=int32)


In [ ]:
print(twod_tensor_indexed[...,0])

tf.Tensor([7 3 2 2 3], shape=(5,), dtype=int32)


In [ ]:
threed_tensor_indexed = tf.random.uniform([4,2,3], minval=2, maxval=10, dtype=tf.dtypes.int32)

In [ ]:
print(threed_tensor_indexed)
print(50*"*", end="\n")
print(threed_tensor_indexed[..., :,2])

tf.Tensor(
[[[9 6 7]
  [6 7 4]]

 [[9 4 9]
  [8 8 4]]

 [[3 6 9]
  [7 5 7]]

 [[2 4 4]
  [8 5 6]]], shape=(4, 2, 3), dtype=int32)
**************************************************
tf.Tensor(
[[7 4]
 [9 4]
 [9 7]
 [4 6]], shape=(4, 2), dtype=int32)


## Tensorflow Math Operations

In [ ]:
x_abs = tf.constant([1, -2, 3])
print(tf.math.abs(x_abs))

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [ ]:
x = tf.constant([[-2.25 + 4.75j]])
tf.abs(x)

<tf.Tensor: shape=(1, 1), dtype=float64, numpy=array([[5.25594901]])>

In [ ]:
x1 = tf.constant([1,2,3,4,5,6])
x2 = tf.constant([5,2,30,41,52,63])

print(tf.add(x1, x2))
print(tf.subtract(x2, x1))

tf.Tensor([ 6  4 33 45 57 69], shape=(6,), dtype=int32)
tf.Tensor([ 4  0 27 37 47 57], shape=(6,), dtype=int32)


In [ ]:
tf.math.acos(
    tf.cast(x1, dtype=tf.float32), name=None
)

<tf.Tensor: shape=(6,), dtype=float32, numpy=array([ 0., nan, nan, nan, nan, nan], dtype=float32)>

In [6]:
x_1 = tf.constant([1,2,3,4,5,6])
x_2 = tf.constant([5])
x_2_streched = tf.constant([5, 5, 5, 5, 5, 5])
x_2_temp = tf.constant([5, 2])

print(tf.add(x_1, x_2)) # this will strech the tensor to the size of x_1 with same value in x_2
print(tf.subtract(x_1, x_2)) # this will strech the tensor to the size of x_1 with same value in x_2
print(tf.add(x_1, x_2_streched))
# print(tf.add(x_1, x_2_temp)) # this will throw and error due to variance in the sizes

tf.Tensor([ 6  7  8  9 10 11], shape=(6,), dtype=int32)
tf.Tensor([-4 -3 -2 -1  0  1], shape=(6,), dtype=int32)
tf.Tensor([ 6  7  8  9 10 11], shape=(6,), dtype=int32)


In [13]:
x = tf.constant([0., 0., 0., 0.,])
y = tf.constant([-2.])
tf.math.maximum(x, y)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>

In [15]:
# arg max
A = tf.constant([2, 20, 30, 3, 6])
print(tf.math.argmax(A))

tf.Tensor(2, shape=(), dtype=int64)


In [18]:
B = tf.constant([[20, 20, 30, 3, 6], [3, 11, 16, 1, 8],
                 [14, 45, 23, 5, 27]])
print(B)
print(tf.math.argmax(B, 0))
print(tf.math.argmax(B, 1))

tf.Tensor(
[[20 20 30  3  6]
 [ 3 11 16  1  8]
 [14 45 23  5 27]], shape=(3, 5), dtype=int32)
tf.Tensor([0 2 0 2 2], shape=(5,), dtype=int64)
tf.Tensor([2 2 1], shape=(3,), dtype=int64)


In [19]:
C = tf.constant([0, 0, 0, 0])
tf.math.argmax(C) # Returns smallest index in case of ties

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [20]:
print(tf.math.argmin(B, 0))
print(tf.math.argmin(B, 1))

tf.Tensor([1 1 1 1 0], shape=(5,), dtype=int64)
tf.Tensor([3 3 3], shape=(3,), dtype=int64)


In [23]:
x = tf.constant([2, 4, 3])
y = tf.constant(2)
print(x.shape)
print(y.shape)
tf.math.equal(x, y)

(3,)
()


<tf.Tensor: shape=(3,), dtype=bool, numpy=array([ True, False, False])>

In [24]:
x = tf.constant([[2, 2], [3, 3]])
y = tf.constant([[8, 16], [2, 3]])
tf.pow(x, y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[  256, 65536],
       [    9,    27]], dtype=int32)>

In [25]:
print(2**8)
print(2**16)
print(3**2)
print(3**3)

256
65536
9
27


In [26]:
tf.pow(tf.constant(2), tf.constant(3))

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [40]:
# math.reduce_sum

print(tensor_two_d)

print(tf.math.reduce_sum(
    tensor_two_d , axis=0, keepdims=False, name=None
))

print(tf.math.reduce_std(
    tf.cast(tensor_two_d, dtype=tf.dtypes.float64) , axis=0, keepdims=False, name=None
))

tf.math.reduce_max(
    tensor_two_d , axis=0, keepdims=False, name=None
)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -2]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)
tf.Tensor([ 7 15 12], shape=(3,), dtype=int32)
tf.Tensor([0.8291562  1.29903811 4.12310563], shape=(3,), dtype=float64)


<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 5, 8], dtype=int32)>

In [43]:
# top k-values; k = 3
result = tf.math.top_k([1, 2, 98, 1, 1, 99, 3, 1, 3, 96, 4, 1],
                        k=3)
result


TopKV2(values=<tf.Tensor: shape=(3,), dtype=int32, numpy=array([99, 98, 96], dtype=int32)>, indices=<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 2, 9], dtype=int32)>)

In [42]:
tf.math.top_k(tensor_two_d)

TopKV2(values=<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[2],
       [5],
       [6],
       [8]], dtype=int32)>, indices=<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[1],
       [1],
       [2],
       [2]], dtype=int32)>)

## Linear Algebra

In [45]:
a = tf.constant([1, 2, 3, 4, 5, 6], shape=[2, 3])
print(a)  # 2-D tensor

b = tf.constant([7, 8, 9, 10, 11, 12], shape=[3, 2])
print(b)  # 2-D tensor

c = tf.matmul(a, b)
print(c)  # `a` * `b`

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 58  64]
 [139 154]], shape=(2, 2), dtype=int32)


In [47]:
import numpy as np

In [49]:
a = tf.constant(np.arange(1, 13, dtype=np.int32), shape=[2, 2, 3])
print(a)  # 3-D tensor

b = tf.constant(np.arange(13, 25, dtype=np.int32), shape=[2, 3, 2])
print(b)  # 3-D tensor


c = tf.matmul(a, b)
c  # `a` * `b`

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)
tf.Tensor(
[[[13 14]
  [15 16]
  [17 18]]

 [[19 20]
  [21 22]
  [23 24]]], shape=(2, 3, 2), dtype=int32)


<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[ 94, 100],
        [229, 244]],

       [[508, 532],
        [697, 730]]], dtype=int32)>

In [50]:
print(a@b)

tf.Tensor(
[[[ 94 100]
  [229 244]]

 [[508 532]
  [697 730]]], shape=(2, 2, 2), dtype=int32)


In [53]:
print(tf.linalg.matrix_transpose(
    a, name='matrix_transpose', conjugate=False
))

print(tf.linalg.matrix_transpose(
    b, name='matrix_transpose', conjugate=False
))

tf.Tensor(
[[[ 1  4]
  [ 2  5]
  [ 3  6]]

 [[ 7 10]
  [ 8 11]
  [ 9 12]]], shape=(2, 3, 2), dtype=int32)
tf.Tensor(
[[[13 15 17]
  [14 16 18]]

 [[19 21 23]
  [20 22 24]]], shape=(2, 2, 3), dtype=int32)


In [54]:
x1 = tf.constant([[0, 0],
                  [0, 2]])

x2 = tf.constant([
    [1, 0, 0],
    [0, 0, 0]
])


print(x1.shape, x2.shape)

(2, 2) (2, 3)


In [56]:
tf.linalg.matmul(x1, x2)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)>

In [57]:
tf.linalg.matmul(x1, x2, a_is_sparse=True, b_is_sparse=True)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)>

In [60]:
two_d_tensor = tf.constant(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
    ], dtype=tf.dtypes.float32
)

print(two_d_tensor)
print(two_d_tensor.shape)

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]], shape=(3, 3), dtype=float32)
(3, 3)


In [61]:
tf.linalg.inv(
  two_d_tensor
)

InvalidArgumentError: ignored

In [67]:
s,u,v = tf.linalg.svd(
 two_d_tensor
)

In [68]:
print(s)
print(u)
print(v)

tf.Tensor([1.6848103e+01 1.0683696e+00 2.8763120e-07], shape=(3,), dtype=float32)
tf.Tensor(
[[ 0.21483716  0.8872305  -0.40824857]
 [ 0.5205872   0.24964423  0.8164965 ]
 [ 0.8263376  -0.3879429  -0.4082481 ]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[ 0.47967106 -0.77669096  0.40824836]
 [ 0.5723676  -0.07568647 -0.81649655]
 [ 0.6650643   0.62531805  0.40824822]], shape=(3, 3), dtype=float32)


In [69]:
# Einsum
a = np.arange(25).reshape(5,5)
b = np.arange(5)
c = np.arange(6).reshape(2,3)

In [74]:
print(a.shape, b.shape, c.shape)

(5, 5) (5,) (2, 3)


In [79]:
print(np.einsum("ij,jk->ik", a,b))
# print(np.einsum(a, [0,0]))
# print(np.trace(a))

ValueError: ignored

In [88]:
a = np.arange(60.).reshape(3,4,5)
b = np.arange(24.).reshape(4,3,2)
print(a)
print(b)
np.einsum('ijk,jil->jl', a, b)

[[[ 0.  1.  2.  3.  4.]
  [ 5.  6.  7.  8.  9.]
  [10. 11. 12. 13. 14.]
  [15. 16. 17. 18. 19.]]

 [[20. 21. 22. 23. 24.]
  [25. 26. 27. 28. 29.]
  [30. 31. 32. 33. 34.]
  [35. 36. 37. 38. 39.]]

 [[40. 41. 42. 43. 44.]
  [45. 46. 47. 48. 49.]
  [50. 51. 52. 53. 54.]
  [55. 56. 57. 58. 59.]]]
[[[ 0.  1.]
  [ 2.  3.]
  [ 4.  5.]]

 [[ 6.  7.]
  [ 8.  9.]
  [10. 11.]]

 [[12. 13.]
  [14. 15.]
  [16. 17.]]

 [[18. 19.]
  [20. 21.]
  [22. 23.]]]


array([[ 1060.,  1390.],
       [ 3640.,  4045.],
       [ 7120.,  7600.],
       [11500., 12055.]])

In [82]:
print(np.einsum("ij->ji", a[0]))

[[ 0.  5. 10. 15.]
 [ 1.  6. 11. 16.]
 [ 2.  7. 12. 17.]
 [ 3.  8. 13. 18.]
 [ 4.  9. 14. 19.]]
