In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

2.14.0


## 1D Tensors

In [3]:
tensor_zero_d = tf.constant(4)

In [4]:
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [8]:
tensor_zero_d = tf.constant([2, 0, -3, 8, 10.])
print(tensor_zero_d)

tf.Tensor([ 2.  0. -3.  8. 10.], shape=(5,), dtype=float32)


## 2D Tensors

In [9]:
tensor_two_d = tf.constant([
    [1, 2, 0],
    [3, 5, -2],
    [1, 5, 6],
    [2, 3, 8],
])

In [10]:
print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -2]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


## 3D Tensors

In [12]:
tensor_three_d = tf.constant([
    [[1, 2, 0],
    [3, 5, -2],
    [1, 5, 6],
    [2, 3, 8],],
    [[1, 2, 0],
    [3, 5, -2],
    [3, 5, -2],
    [2, 3, 8],],
])

In [13]:
print(tensor_three_d)

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -2]
  [ 1  5  6]
  [ 2  3  8]]

 [[ 1  2  0]
  [ 3  5 -2]
  [ 3  5 -2]
  [ 2  3  8]]], shape=(2, 4, 3), dtype=int32)
