In [2]:
import tensorflow as tf

In [3]:
print(tf.__version__)

2.14.0


## 1D Tensors

In [ ]:
tensor_zero_d = tf.constant(4)

In [ ]:
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [13]:
tensor_zero_d = tf.constant([2, 0, -3, 8, 10.])
print(tensor_zero_d)

tf.Tensor([ 2.  0. -3.  8. 10.], shape=(5,), dtype=float32)


In [14]:
casted_tensor_zero_d = tf.cast(
    tensor_zero_d, dtype=tf.int64
)

In [15]:
print(casted_tensor_zero_d)

tf.Tensor([ 2  0 -3  8 10], shape=(5,), dtype=int64)


In [16]:
tf.cast(
    tensor_zero_d, dtype=bool
)

<tf.Tensor: shape=(5,), dtype=bool, numpy=array([ True, False,  True,  True,  True])>

## 2D Tensors

In [ ]:
tensor_two_d = tf.constant([
    [1, 2, 0],
    [3, 5, -2],
    [1, 5, 6],
    [2, 3, 8],
])

In [ ]:
print(tensor_two_d)
print(tensor_two_d.ndim)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -2]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)
2


## 3D Tensors

In [ ]:
tensor_three_d = tf.constant([
    [[1, 2, 0],
    [3, 5, -2],
    [1, 5, 6],
    [2, 3, 8],],
    [[1, 2, 0],
    [3, 5, -2],
    [3, 5, -2],
    [2, 3, 8],],
])

In [ ]:
print(tensor_three_d)

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -2]
  [ 1  5  6]
  [ 2  3  8]]

 [[ 1  2  0]
  [ 3  5 -2]
  [ 3  5 -2]
  [ 2  3  8]]], shape=(2, 4, 3), dtype=int32)


In [ ]:
print(tensor_three_d.shape)

(2, 4, 3)


In [ ]:
print(tensor_three_d.ndim)

3


## 4D Tensors

In [7]:
tensor_four_d = tf.constant([
      [
        [[1, 2, 0],
        [2, 3, 8],],

        [[1, 2, 0],
        [2, 3, 8],],

        [[1, 2, 0],
        [2, 3, 8],],

        [[1, 2, 0],
        [2, 3, 8],],
      ],
      [
        [[5, 25, 123],
        [235, 3, 198],],

        [[1, 21, 53],
        [200, 328, 8],],

        [[15, 23, 5],
        [2, 3, 89],],

        [[1, 2, 90],
        [22, 36, 87],],
      ],
      [
        [[5, 25, 123],
        [235, 3, 198],],

        [[1, 21, 53],
        [200, 328, 8],],

        [[15, 23, 5],
        [2, 3, 89],],

        [[1, 2, 90],
        [22, 36, 87],],
      ]
], dtype=tf.float32)

In [8]:
print(tensor_four_d)
print(tensor_four_d.shape)
print(tensor_four_d.ndim)

tf.Tensor(
[[[[  1.   2.   0.]
   [  2.   3.   8.]]

  [[  1.   2.   0.]
   [  2.   3.   8.]]

  [[  1.   2.   0.]
   [  2.   3.   8.]]

  [[  1.   2.   0.]
   [  2.   3.   8.]]]


 [[[  5.  25. 123.]
   [235.   3. 198.]]

  [[  1.  21.  53.]
   [200. 328.   8.]]

  [[ 15.  23.   5.]
   [  2.   3.  89.]]

  [[  1.   2.  90.]
   [ 22.  36.  87.]]]


 [[[  5.  25. 123.]
   [235.   3. 198.]]

  [[  1.  21.  53.]
   [200. 328.   8.]]

  [[ 15.  23.   5.]
   [  2.   3.  89.]]

  [[  1.   2.  90.]
   [ 22.  36.  87.]]]], shape=(3, 4, 2, 3), dtype=float32)
(3, 4, 2, 3)
4


## Complex Data Type

In [12]:
real = tf.constant([2.25])
imag = tf.constant([4.75])
tf.complex(real, imag)

<tf.Tensor: shape=(1,), dtype=complex64, numpy=array([2.25+4.75j], dtype=complex64)>