In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

2.14.0


## 1D Tensors

In [ ]:
tensor_zero_d = tf.constant(4)

In [ ]:
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
tensor_zero_d = tf.constant([2, 0, -3, 8, 10.])
print(tensor_zero_d)

tf.Tensor([ 2.  0. -3.  8. 10.], shape=(5,), dtype=float32)


In [ ]:
casted_tensor_zero_d = tf.cast(
    tensor_zero_d, dtype=tf.int64
)

In [ ]:
print(casted_tensor_zero_d)

tf.Tensor([ 2  0 -3  8 10], shape=(5,), dtype=int64)


In [ ]:
tf.cast(
    tensor_zero_d, dtype=bool
)

<tf.Tensor: shape=(5,), dtype=bool, numpy=array([ True, False,  True,  True,  True])>

## 2D Tensors

In [ ]:
tensor_two_d = tf.constant([
    [1, 2, 0],
    [3, 5, -2],
    [1, 5, 6],
    [2, 3, 8],
])

In [ ]:
print(tensor_two_d)
print(tensor_two_d.ndim)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -2]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)
2


## 3D Tensors

In [ ]:
tensor_three_d = tf.constant([
    [[1, 2, 0],
    [3, 5, -2],
    [1, 5, 6],
    [2, 3, 8],],
    [[1, 2, 0],
    [3, 5, -2],
    [3, 5, -2],
    [2, 3, 8],],
])

In [ ]:
print(tensor_three_d)

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -2]
  [ 1  5  6]
  [ 2  3  8]]

 [[ 1  2  0]
  [ 3  5 -2]
  [ 3  5 -2]
  [ 2  3  8]]], shape=(2, 4, 3), dtype=int32)


In [ ]:
print(tensor_three_d.shape)

(2, 4, 3)


In [ ]:
print(tensor_three_d.ndim)

3


## 4D Tensors

In [ ]:
tensor_four_d = tf.constant([
      [
        [[1, 2, 0],
        [2, 3, 8],],

        [[1, 2, 0],
        [2, 3, 8],],

        [[1, 2, 0],
        [2, 3, 8],],

        [[1, 2, 0],
        [2, 3, 8],],
      ],
      [
        [[5, 25, 123],
        [235, 3, 198],],

        [[1, 21, 53],
        [200, 328, 8],],

        [[15, 23, 5],
        [2, 3, 89],],

        [[1, 2, 90],
        [22, 36, 87],],
      ],
      [
        [[5, 25, 123],
        [235, 3, 198],],

        [[1, 21, 53],
        [200, 328, 8],],

        [[15, 23, 5],
        [2, 3, 89],],

        [[1, 2, 90],
        [22, 36, 87],],
      ]
], dtype=tf.float32)

In [ ]:
print(tensor_four_d)
print(tensor_four_d.shape)
print(tensor_four_d.ndim)

tf.Tensor(
[[[[  1.   2.   0.]
   [  2.   3.   8.]]

  [[  1.   2.   0.]
   [  2.   3.   8.]]

  [[  1.   2.   0.]
   [  2.   3.   8.]]

  [[  1.   2.   0.]
   [  2.   3.   8.]]]


 [[[  5.  25. 123.]
   [235.   3. 198.]]

  [[  1.  21.  53.]
   [200. 328.   8.]]

  [[ 15.  23.   5.]
   [  2.   3.  89.]]

  [[  1.   2.  90.]
   [ 22.  36.  87.]]]


 [[[  5.  25. 123.]
   [235.   3. 198.]]

  [[  1.  21.  53.]
   [200. 328.   8.]]

  [[ 15.  23.   5.]
   [  2.   3.  89.]]

  [[  1.   2.  90.]
   [ 22.  36.  87.]]]], shape=(3, 4, 2, 3), dtype=float32)
(3, 4, 2, 3)
4


## Complex Data Type

In [ ]:
real = tf.constant([2.25])
imag = tf.constant([4.75])
tf.complex(real, imag)

<tf.Tensor: shape=(1,), dtype=complex64, numpy=array([2.25+4.75j], dtype=complex64)>

## Tensor String

In [3]:
tensor_string = tf.constant(["hello world", "hi"])
print(tensor_string)

tf.Tensor([b'hello world' b'hi'], shape=(2,), dtype=string)


## Numpy to Tensorflow

In [4]:
import numpy as np

In [5]:
np_array = np.array([1,2,3])

In [6]:
print(np_array.shape)

(3,)


In [7]:
converted_tensor = tf.convert_to_tensor(np_array)

In [8]:
print(converted_tensor)

tf.Tensor([1 2 3], shape=(3,), dtype=int64)


In [26]:
#let's us create multi dimensional identity matrix tensors using tf.eye function
tf.eye(
    num_rows=5,
    num_columns=None,
    batch_shape=[3],
    dtype=tf.dtypes.bool,
    name=None
)

<tf.Tensor: shape=(3, 5, 5), dtype=bool, numpy=
array([[[ True, False, False, False, False],
        [False,  True, False, False, False],
        [False, False,  True, False, False],
        [False, False, False,  True, False],
        [False, False, False, False,  True]],

       [[ True, False, False, False, False],
        [False,  True, False, False, False],
        [False, False,  True, False, False],
        [False, False, False,  True, False],
        [False, False, False, False,  True]],

       [[ True, False, False, False, False],
        [False,  True, False, False, False],
        [False, False,  True, False, False],
        [False, False, False,  True, False],
        [False, False, False, False,  True]]])>

In [31]:
#tensors filled with 1
tf.ones(
    [2,3,2,2],
    dtype=tf.dtypes.float16,
    name=None,
    layout=None
)

<tf.Tensor: shape=(2, 3, 2, 2), dtype=float16, numpy=
array([[[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]], dtype=float16)>

In [34]:
#tensors filled with 0
tf.zeros(
    [2,],
    dtype=tf.dtypes.float16,
    name=None,
    layout=None
)

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([0., 0.], dtype=float16)>

In [42]:
#tensors filled with custom values
tensor_ten_filled = tf.fill(
    [2,2,3],
    2*5.0,
)

In [43]:
#gives a tensor filled with 1 of the similar shape of the tensor given as input.
tf.ones_like(tensor_ten_filled)

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [50]:
random_tensor = tf.constant([
    [1,1,1],
    [1,1,1],
    [1,1,1],
])
print(random_tensor)

tf.Tensor(
[[1 1 1]
 [1 1 1]
 [1 1 1]], shape=(3, 3), dtype=int32)


In [52]:
print(tf.shape(random_tensor))
print(tf.size(random_tensor))
print(tf.rank(random_tensor))

tf.Tensor([3 3], shape=(2,), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


## Tensors from Normal Distribution

In [ ]:
tf.random.normal(
    shape,
    mean=0.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
